INSERT INTO countryname (name) VALUES ('Afghanistan');
INSERT INTO countryname (name) VALUES ('Africa');
INSERT INTO countryname (name) VALUES ('Alabama');
INSERT INTO countryname (name) VALUES ('Alaska');
INSERT INTO countryname (name) VALUES ('Albania');
INSERT INTO countryname (name) VALUES ('Algeria');
INSERT INTO countryname (name) VALUES ('Andorra');
INSERT INTO countryname (name) VALUES ('Angola');
INSERT INTO countryname (name) VALUES ('Antigua and Barbuda');
INSERT INTO countryname (name) VALUES ('Arabic');
INSERT INTO countryname (name) VALUES ('Argentina');
INSERT INTO countryname (name) VALUES ('Armenia');
INSERT INTO countryname (name) VALUES ('Aruba');
INSERT INTO countryname (name) VALUES ('Australia');
INSERT INTO countryname (name) VALUES ('Austria');
INSERT INTO countryname (name) VALUES ('Azerbaijan');
INSERT INTO countryname (name) VALUES ('Bahamas');
INSERT INTO countryname (name) VALUES ('Bangladesh');
INSERT INTO countryname (name) VALUES ('Barbados');
INSERT INTO countryname (name) VALUES ('Belarus');
INSERT INTO countryname (name) VALUES ('Belgium');
INSERT INTO countryname (name) VALUES ('Belize');
INSERT INTO countryname (name) VALUES ('Benin');
INSERT INTO countryname (name) VALUES ('Bermuda');
INSERT INTO countryname (name) VALUES ('Bolivia');
INSERT INTO countryname (name) VALUES ('Bosnia and Herzegovina');
INSERT INTO countryname (name) VALUES ('Brazil');
INSERT INTO countryname (name) VALUES ('Brunei');
INSERT INTO countryname (name) VALUES ('Bulgaria');
INSERT INTO countryname (name) VALUES ('Burkina Faso');
INSERT INTO countryname (name) VALUES ('Burundi');
INSERT INTO countryname (name) VALUES ('Cambodia');
INSERT INTO countryname (name) VALUES ('Cameroon');
INSERT INTO countryname (name) VALUES ('Canada');
INSERT INTO countryname (name) VALUES ('Cayman Island');
INSERT INTO countryname (name) VALUES ('Chile');
INSERT INTO countryname (name) VALUES ('China');
INSERT INTO countryname (name) VALUES ('Colombia');
INSERT INTO countryname (name) VALUES ('Congo');
INSERT INTO countryname (name) VALUES ('Costa Rica');
INSERT INTO countryname (name) VALUES ('Croatia');
INSERT INTO countryname (name) VALUES ('Cuba');
INSERT INTO countryname (name) VALUES ('Cyprus');
INSERT INTO countryname (name) VALUES ('Czech Republic');
INSERT INTO countryname (name) VALUES ('Denmark');
INSERT INTO countryname (name) VALUES ('Dominica');
INSERT INTO countryname (name) VALUES ('Dominican Republic');
INSERT INTO countryname (name) VALUES ('Ecuador');
INSERT INTO countryname (name) VALUES ('Egypt');
INSERT INTO countryname (name) VALUES ('El Salvador');
INSERT INTO countryname (name) VALUES ('English');
INSERT INTO countryname (name) VALUES ('Estonia');
INSERT INTO countryname (name) VALUES ('Ethiopia');
INSERT INTO countryname (name) VALUES ('Faroe Islands');
INSERT INTO countryname (name) VALUES ('Fiji');
INSERT INTO countryname (name) VALUES ('Finland');
INSERT INTO countryname (name) VALUES ('France');
INSERT INTO countryname (name) VALUES ('Gambia');
INSERT INTO countryname (name) VALUES ('Georgia');
INSERT INTO countryname (name) VALUES ('Germany');
INSERT INTO countryname (name) VALUES ('Ghana');
INSERT INTO countryname (name) VALUES ('Greece');
INSERT INTO countryname (name) VALUES ('Greenland');
INSERT INTO countryname (name) VALUES ('Grenada');
INSERT INTO countryname (name) VALUES ('Guadeloupe');
INSERT INTO countryname (name) VALUES ('Guatemala');
INSERT INTO countryname (name) VALUES ('Guinea');
INSERT INTO countryname (name) VALUES ('Guyana');
INSERT INTO countryname (name) VALUES ('Haiti');
INSERT INTO countryname (name) VALUES ('Honduras');
INSERT INTO countryname (name) VALUES ('Hong Kong');
INSERT INTO countryname (name) VALUES ('Hungary');
INSERT INTO countryname (name) VALUES ('Iceland');
INSERT INTO countryname (name) VALUES ('India');
INSERT INTO countryname (name) VALUES ('Indonesia');
INSERT INTO countryname (name) VALUES ('Iran');
INSERT INTO countryname (name) VALUES ('Iraq');
INSERT INTO countryname (name) VALUES ('Ireland');
INSERT INTO countryname (name) VALUES ('Israel');
INSERT INTO countryname (name) VALUES ('Italy');
INSERT INTO countryname (name) VALUES ('Ivory Coast');
INSERT INTO countryname (name) VALUES ('Jamaica');
INSERT INTO countryname (name) VALUES ('Japan');
INSERT INTO countryname (name) VALUES ('Jordan');
INSERT INTO countryname (name) VALUES ('Kazakhstan');
INSERT INTO countryname (name) VALUES ('Kenya');
INSERT INTO countryname (name) VALUES ('Korea');
INSERT INTO countryname (name) VALUES ('Kosovo');
INSERT INTO countryname (name) VALUES ('Kuwait');
INSERT INTO countryname (name) VALUES ('Kyrgyzstan');
INSERT INTO countryname (name) VALUES ('Latvia');
INSERT INTO countryname (name) VALUES ('Lebanon');
INSERT INTO countryname (name) VALUES ('Liberia');
INSERT INTO countryname (name) VALUES ('Lithuania');
INSERT INTO countryname (name) VALUES ('Luxembourg');
INSERT INTO countryname (name) VALUES ('Macedonia');
INSERT INTO countryname (name) VALUES ('Madagascar');
INSERT INTO countryname (name) VALUES ('Malaysia');
INSERT INTO countryname (name) VALUES ('Maldives');
INSERT INTO countryname (name) VALUES ('Mali');
INSERT INTO countryname (name) VALUES ('Malta');
INSERT INTO countryname (name) VALUES ('Martinique');
INSERT INTO countryname (name) VALUES ('Mauritius');
INSERT INTO countryname (name) VALUES ('Mexico');
INSERT INTO countryname (name) VALUES ('Mix');
INSERT INTO countryname (name) VALUES ('Moldova');
INSERT INTO countryname (name) VALUES ('Monaco');
INSERT INTO countryname (name) VALUES ('Mongolia');
INSERT INTO countryname (name) VALUES ('Montenegro');
INSERT INTO countryname (name) VALUES ('Morocco');
INSERT INTO countryname (name) VALUES ('Namibia');
INSERT INTO countryname (name) VALUES ('Nepal');
INSERT INTO countryname (name) VALUES ('Netherlands');
INSERT INTO countryname (name) VALUES ('Netherlands Antilles');
INSERT INTO countryname (name) VALUES ('New Zealand');
INSERT INTO countryname (name) VALUES ('Nicaragua');
INSERT INTO countryname (name) VALUES ('Nigeria');
INSERT INTO countryname (name) VALUES ('Norway');
INSERT INTO countryname (name) VALUES ('Oman');
INSERT INTO countryname (name) VALUES ('Pakistan');
INSERT INTO countryname (name) VALUES ('Palestine');
INSERT INTO countryname (name) VALUES ('Panama');
INSERT INTO countryname (name) VALUES ('Paraguay');
INSERT INTO countryname (name) VALUES ('Persian');
INSERT INTO countryname (name) VALUES ('Peru');
INSERT INTO countryname (name) VALUES ('Philippines');
INSERT INTO countryname (name) VALUES ('Poland');
INSERT INTO countryname (name) VALUES ('Portugal');
INSERT INTO countryname (name) VALUES ('Puerto Rico');
INSERT INTO countryname (name) VALUES ('Qatar');
INSERT INTO countryname (name) VALUES ('Romania');
INSERT INTO countryname (name) VALUES ('Russia');
INSERT INTO countryname (name) VALUES ('Rwanda');
INSERT INTO countryname (name) VALUES ('Saint Kitts and Nevis');
INSERT INTO countryname (name) VALUES ('Saint Lucia');
INSERT INTO countryname (name) VALUES ('Saint Vincent');
INSERT INTO countryname (name) VALUES ('Saudi Arabia');
INSERT INTO countryname (name) VALUES ('Senegal');
INSERT INTO countryname (name) VALUES ('Serbia');
INSERT INTO countryname (name) VALUES ('Singapore');
INSERT INTO countryname (name) VALUES ('Slovakia');
INSERT INTO countryname (name) VALUES ('Slovenia');
INSERT INTO countryname (name) VALUES ('Somalia');
INSERT INTO countryname (name) VALUES ('South Africa');
INSERT INTO countryname (name) VALUES ('South Korea');
INSERT INTO countryname (name) VALUES ('Spain');
INSERT INTO countryname (name) VALUES ('Sri Lanka');
INSERT INTO countryname (name) VALUES ('Suriname');
INSERT INTO countryname (name) VALUES ('Sweden');
INSERT INTO countryname (name) VALUES ('Switzerland');
INSERT INTO countryname (name) VALUES ('Syria');
INSERT INTO countryname (name) VALUES ('Taiwan');
INSERT INTO countryname (name) VALUES ('Tajikistan');
INSERT INTO countryname (name) VALUES ('Tamil');
INSERT INTO countryname (name) VALUES ('Tanzania');
INSERT INTO countryname (name) VALUES ('Thailand');
INSERT INTO countryname (name) VALUES ('Trinidad and Tobago');
INSERT INTO countryname (name) VALUES ('Tunisia');
INSERT INTO countryname (name) VALUES ('Turkey');
INSERT INTO countryname (name) VALUES ('Uganda');
INSERT INTO countryname (name) VALUES ('UK');
INSERT INTO countryname (name) VALUES ('Ukraine');
INSERT INTO countryname (name) VALUES ('United Arab Emirates');
INSERT INTO countryname (name) VALUES ('Uruguay');
INSERT INTO countryname (name) VALUES ('USA');
INSERT INTO countryname (name) VALUES ('Uzbekistan');
INSERT INTO countryname (name) VALUES ('Venezuela');
INSERT INTO countryname (name) VALUES ('Vietnam');
INSERT INTO countryname (name) VALUES ('Virgin Islands');
INSERT INTO countryname (name) VALUES ('Zambia');
INSERT INTO countryname (name) VALUES ('Zimbabwe');
